In [27]:
import ephem
import math


# Set the geographical coordinates of the location where you want to perform the calculation
latitude = '48.8566'  # Latitude of Paris
longitude = '2.3522'  # Longitude of Paris


# Create an object to represent the sun
sun = ephem.Sun()

# Set the date and time for which you want to calculate the azimuth and elevation
date = ephem.Date("2023/06/21 11:00:00")
print(date)
# Create an observer object from the geographical coordinates
observer = ephem.Observer()
observer.lat = latitude
observer.lon = longitude

# Set the date and time for the observer
observer.date = date

# Calculate the azimuth and elevation of the sun
sun.compute(observer)

# Get the calculated values in radians
azimuth_rad = sun.az
elevation_rad = sun.alt
print(azimuth_rad, elevation_rad)
# Convert radians to degrees
azimuth_deg = math.degrees(azimuth_rad)
elevation_deg = math.degrees(elevation_rad)

# Display the results
print("Azimuth of the sun:", azimuth_deg)
print("Elevation of the sun:", elevation_deg)


2023/6/21 11:00:00
153:11:46.3 62:34:11.0
Azimuth of the sun: 153.19618436604858
Elevation of the sun: 62.56973057127518


In [31]:
# Create a geocoder object
geolocator = Nominatim(user_agent="my_app")

# Get the location of Paris
location = geolocator.geocode('Paris')

# Extract the latitude and longitude
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

# Create an object to represent the sun
sun = ephem.Sun()

# Set the date and time for which you want to calculate the azimuth and elevation
date = ephem.Date("2023/06/21 10:00:00")
print(date)
# Create an observer object from the geographical coordinates
observer = ephem.Observer()
observer.lat = str(latitude)
observer.lon = str(longitude)

# Set the date and time for the observer
observer.date = date

# Calculate the azimuth and elevation of the sun
sun.compute(observer)

# Get the calculated values in radians
azimuth_rad = sun.az
elevation_rad = sun.alt
print(azimuth_rad, elevation_rad)
# Convert radians to degrees
azimuth_deg = math.degrees(azimuth_rad)
elevation_deg = math.degrees(elevation_rad)

# Display the results
print("Azimuth of the sun:", azimuth_deg)
print("Elevation of the sun:", elevation_deg)

48.8534951 2.3483915
2023/6/21 10:00:00
128:50:06.7 56:19:30.4
Azimuth of the sun: 128.83520820055256
Elevation of the sun: 56.3251208395643


In [35]:
import pytz
from datetime import datetime

# Define the timezone for Paris
paris_tz = pytz.timezone('Europe/Paris')

# Create a datetime object in the Paris timezone
paris_dt = paris_tz.localize(datetime(2023, 6, 21, 12, 0, 0))

# Convert the datetime to UTC
utc_dt = paris_dt.astimezone(pytz.utc)
print(utc_dt)
# Format the UTC datetime
formatted_utc_dt = utc_dt.strftime('%Y-%m-%d %H:%M:%S')

# Print the formatted UTC datetime
print(formatted_utc_dt)


2023-06-21 10:00:00+00:00
2023-06-21 10:00:00


In [36]:
from osgeo import gdal

# Open the TIFF file
dataset = gdal.Open('/work/EOLAB/DATA/MNS/Paris/75-2021-0643-6862-LA93-0M50.tif')

# Get the geotransform information
geotransform = dataset.GetGeoTransform()

# Extract the pixel size in X and Y directions
pixel_size_x = geotransform[1]
pixel_size_y = geotransform[5]

# Get the spatial reference system
srs = dataset.GetProjection()

# Close the dataset
dataset = None

# Print the resolution in meters
print("Resolution in X direction:", abs(pixel_size_x), "meters")
print("Resolution in Y direction:", abs(pixel_size_y), "meters")


Resolution in X direction: 0.5 meters
Resolution in Y direction: 0.5 meters


In [7]:
from datetime import datetime, timedelta

start_date = datetime.strptime('2023-05-31', "%Y-%m-%d")
end_date = datetime.strptime('2023-06-10', "%Y-%m-%d")
step = timedelta(days=int(1))

# Generate the range of dates
dates = []
current_date = start_date
while current_date <= end_date:
    dates.append(current_date)
    current_date += step

In [9]:
from datetime import datetime

# Define the date and list of times
date = datetime(2023, 1, 1)
times = ['09:00', '12:30', '15:45']

# Create a list of datetime objects
datetime_list = []
for time in times:
    time_obj = datetime.strptime(time, '%H:%M')
    datetime_obj = datetime(date.year, date.month, date.day, time_obj.hour, time_obj.minute)
    datetime_list.append(datetime_obj)

# Print the list of datetime objects
for dt in datetime_list:
    print(dt)


2023-01-01 09:00:00
2023-01-01 12:30:00
2023-01-01 15:45:00


In [13]:
from datetime import datetime, timedelta

# Define the start time, end time, and step
start_time = '09:00'
end_time = '17:00'
step = 30

# Parse the start time and end time
start_datetime = datetime.strptime(start_time, '%H:%M')
end_datetime = datetime.strptime(end_time, '%H:%M')

# Generate the list of times
time_list = []
current_datetime = start_datetime
while current_datetime <= end_datetime:
    time_list.append(current_datetime.strftime('%H:%M'))
    current_datetime += timedelta(minutes=step)

# Print the list of times
for time in time_list:
    print(time)


09:00
09:30
10:00
10:30
11:00
11:30
12:00
12:30
13:00
13:30
14:00
14:30
15:00
15:30
16:00
16:30
17:00


In [16]:
from geopy.geocoders import Nominatim

# Create a geocoder object
geolocator = Nominatim(user_agent="my_app")

# Get the location of Paris
location = geolocator.geocode("Paris")

# Extract the latitude and longitude
latitude = location.latitude
longitude = location.longitude

# Print the latitude and longitude
print("Latitude:", latitude)
print("Longitude:", longitude)


Latitude: 48.8534951
Longitude: 2.3483915


In [45]:
import os
os.path.splitext(os.path.basename('/work/EOLAB/DATA/MNS/Paris/75-2021-0643-6862-LA93-0M50.tif'))[0]



'75-2021-0643-6862-LA93-0M50'

In [5]:
import os
import glob

# List of files
file_list = glob.glob("/work/EOLAB/DATA/MNS/Paris/*.tif")

# Output file path
output_file = "listing.lst"

# Open the output file in write mode
with open(output_file, "w") as f:
    # Iterate over the file list
    for file in file_list:
        # Get the absolute path of each file
        file_path = os.path.abspath(file)
        # Write the file path to the output file
        f.write(file_path + "\n")

In [24]:
import gdal
# Output mosaic file

files = glob.glob("outputs/*1530*")

output_file = "mosaic-" + files[0][-27:]
print(output_file)

print(files)

g = gdal.Warp(output_file, files, format='GTIFF')
g = None
# Close the mosaic dataset

mosaic-hillshade-20230531-1530.tif
['outputs/75-2021-0647-6861-LA93-0M50-hillshade-20230531-1530.tif', 'outputs/75-2021-0651-6865-LA93-0M50-hillshade-20230531-1530.tif', 'outputs/75-2021-0643-6862-LA93-0M50-hillshade-20230531-1530.tif', 'outputs/75-2021-0647-6862-LA93-0M50-hillshade-20230531-1530.tif', 'outputs/75-2021-0653-6866-LA93-0M50-hillshade-20230531-1530.tif']


In [2]:
import re

error_message = "ValueError: The radius (option --radius, value=2983) must be strictly less than half the size of the window (option --window_size, value=1024)"
re.search(r"value=(\d+)", error_message).group(1)

'2983'

In [3]:
646 < (1024 / 2)

False

In [1]:
from datetime import datetime

# Create a datetime object
dt = datetime(2023, 11, 16, 12, 30, 0)

# Convert the datetime to a float timestamp
timestamp = dt.timestamp()
print(timestamp)


1700137800.0


# Obtenir mask ombre soleil

In [6]:
import rasterio
import numpy as np
from datetime import datetime
import glob

# List of paths to your input rasters
input_raster_paths = ["outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1300.tif", 
                      "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1330.tif",
                      "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1400.tif",
                      "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1430.tif",
                      "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1500.tif"]

times = [datetime.strptime(date_string[-17:-4], "%Y%m%d-%H%M") for date_string in input_raster_paths]
timestamps = [int(time.timestamp()) for time in times]

with rasterio.open(input_raster_paths[0]) as src:
    height = src.height
    width = src.width
    profile = src.profile

# Initialize variables to store the time of changes
from_1_to_0 = np.full((height, width), np.nan)  # Initialize with infinity
from_0_to_1 = np.full((height, width), np.nan)  # Initialize with infinity
previous_mask = np.full((height, width), 1.) # Initialize to dark

# Iterate through the input rasters
for path, time, timestamp in zip(input_raster_paths, times, timestamps):
    print(timestamp)
    with rasterio.open(path) as src:
        data = src.read(1)  # Read the raster data
        print("mask time", time, data)
        print('\n')
        mask_changes_1_to_0 = (previous_mask == 1.) & (data == 0.)  # Identify pixels changing from 1 to 0
        mask_changes_0_to_1 = (previous_mask == 0.) & (data == 1.)  # Identify pixels changing from 0 to 1
        from_1_to_0[mask_changes_1_to_0] = timestamp # Update time for pixels changing from 1 to 0
        from_0_to_1[mask_changes_0_to_1] = timestamp # Update time for pixels changing from 0 to 1
        
        previous_mask = data

print(from_1_to_0)
# # Create new rasters to store the time of changes
with rasterio.open('from_1_to_0.tif', 'w', **profile) as dst:
    dst.write(from_1_to_0, 1)  # Write the time of changes from 1 to 0 to the new raster
with rasterio.open('from_0_to_1.tif', 'w', **profile) as dst:
    dst.write(from_0_to_1, 1)  # Write the time of changes from 0 to 1 to the new raster


1717160400
mask time 2024-05-31 13:00:00 [[0. 0. 0. ... 1. 1. 1.]
 [1. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


1717162200
mask time 2024-05-31 13:30:00 [[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


1717164000
mask time 2024-05-31 14:00:00 [[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


1717165800
mask time 2024-05-31 14:30:00 [[0. 0. 0. ... 1. 1. 1.]
 [1. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


1717167600
mask time 2024-05-31 15:00:00 [[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


[[1.7

In [32]:
sun_to_shadow = gpd.read_file('sun_to_shadow.gpkg', layer='sun_to_shadow')
shadow_to_sun = gpd.read_file('shadow_to_sun.gpkg', layer='shadow_to_sun')

In [34]:
intersection = gpd.overlay(sun_to_shadow, shadow_to_sun, how='intersection')

/usr/local/lib/python3.8/dist-packages/geopandas/geodataframe.py:1803: FutureWarning: `unary_union` returned None due to all-None GeoSeries. In future, `unary_union` will return 'GEOMETRYCOLLECTION EMPTY' instead.
  merged_geom = block.unary_union
/tmp/slurm-2493866/ipykernel_229211/3722783468.py:1: UserWarning: `keep_geom_type=True` in overlay resulted in 47997 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  intersection = gpd.overlay(sun_to_shadow, shadow_to_sun, how='intersection')


In [36]:
intersection.to_file('intersections.gpkg')

In [3]:
raster_paths = ["outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1300.tif", 
              "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1330.tif",
              "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1400.tif",
              "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1430.tif",
              "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1500.tif"]
              # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1530.tif",
              # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1600.tif",
              #   "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1630.tif",
              #   "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1700.tif"]
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1730.tif",
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1800.tif",
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1830.tif",
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1900.tif"]
raster_arrays = []
for path in raster_paths:
    with rasterio.open(path) as src:
        raster_arrays.append(src.read(1))

# Initialize counters for changes from 1 to 0 and 0 to 1
changes_1_to_0 = np.zeros_like(raster_arrays[0])
changes_0_to_1 = np.zeros_like(raster_arrays[0])

# Compare corresponding pixels across the arrays to identify changes
for i in range(len(raster_arrays) - 1):
    changes_1_to_0 += np.logical_and(raster_arrays[i] == 1, raster_arrays[i + 1] == 0)
    changes_0_to_1 += np.logical_and(raster_arrays[i] == 0, raster_arrays[i + 1] == 1)

In [4]:
print(np.unique(changes_0_to_1, return_counts=True))
print(np.unique(changes_1_to_0, return_counts=True))

(array([0., 1., 2.], dtype=float32), array([3667279,  330050,    2671]))
(array([0., 1., 2.], dtype=float32), array([3699796,  290402,    9802]))


In [5]:
c, s = np.unique(changes_0_to_1 + changes_1_to_0, return_counts=True)

In [8]:
timestamps

[1717160400, 1717162200, 1717164000, 1717165800, 1717167600]

In [67]:
changes_0_to_1 + changes_1_to_0 >

array([[0., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]], dtype=float32)

In [9]:
start_sun = np.full((height, width), 0.)  # Initialize with infinity
end_sun = np.full((height, width), 0.)  # Initialize with infinity
# previous_mask = np.full((height, width), 1.) # Initialize to dark

# Iterate through the input rasters
for path,timestamp in zip(raster_paths,timestamps):
    with rasterio.open(path) as src:
        data = src.read(1)  # Read the raster data
        mask_start_sun = (start_sun == 0.) & (data == 0.)  # Identify pixels changing from 1 to 0
        mask_end_sun = (start_sun != 0.) & (data == 1.) & (end_sun == 0.) # Identify pixels changing from 0 to 1
        start_sun[mask_start_sun] = timestamp # Update time for pixels changing from 1 to 0
        end_sun[mask_end_sun] = timestamp # Update time for pixels changing from 0 to 1
        

In [10]:
np.unique(start_sun, return_counts=True)

(array([0.0000000e+00, 1.7171604e+09, 1.7171622e+09, 1.7171640e+09,
        1.7171658e+09, 1.7171676e+09]),
 array([ 273211, 3445764,  102024,   61822,   40113,   77066]))

In [11]:
np.unique(end_sun, return_counts=True)

(array([0.0000000e+00, 1.7171622e+09, 1.7171640e+09, 1.7171658e+09,
        1.7171676e+09]),
 array([3667279,   39289,   49969,   98960,  144503]))

In [12]:
np.logical_and(start_sun > end_sun,end_sun != 0.).sum()

0

A faire : 
- créer deux raster avec les timestamp (0, times et nodata pour les valeurs non valides (+ de 2 changements)
- Les passer en vecteurs (voir si ya pas trop de géometries dispatchées)
- Les merger et checker la cohérence des deux timestamp (start and en sun)
- Vérifier la cohérence et si ya toujours suffisamment de vecteurs dans la totalité de la zone.


In [ ]:
import rasterio
from shapely.geometry import MultiPolygon
from shapely.ops import unary_union
import numpy as np 
import geopandas as gpd
from datetime import datetime
import glob
from osgeo import gdal, ogr, osr
import time
import pandas as pd

def coded_raster(stacked_array):
    # reshape array
    data_2d = stacked_array.reshape(-1, 4)

    # get quadruples
    unique_quadruplets, _ = np.unique(data_2d, axis=0, return_inverse=True)
        
    # create dict
    quadruplet_dict = {tuple(q): i + 1 for i, q in enumerate(unique_quadruplets)}
        
    # create coded raster
    new_array = np.array([[quadruplet_dict[tuple(stacked_array[i, j, :])] for j in range(stacked_array.shape[1])] for i in range(stacked_array.shape[0])])

    return new_array, quadruplet_dict

In [44]:
raster_paths = sorted(glob.glob("../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-*.tif"))

In [45]:
raster_paths

['../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-0800.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-0830.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-0900.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-0930.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1000.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1030.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1100.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1130.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1200.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1230.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1300.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1330.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1400.tif',
 '../outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1430.tif',
 '../o

In [46]:
raster_paths = raster_paths[:25]

In [47]:
# raster_paths = ["outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1300.tif", 
#               "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1330.tif",
#               "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1400.tif",
#               "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1430.tif",
#               "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1500.tif"]
              # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1530.tif",
              # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1600.tif",
              #   "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1630.tif",
              #   "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1700.tif"]
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1730.tif",
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1800.tif",
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1830.tif",
                # "outputs/75-2021-0647-6863-LA93-0M50-hillshade-20240531-1900.tif"]
                
with rasterio.open(raster_paths[0]) as src:
    height = src.height
    width = src.width
    profile = src.profile

times = [datetime.strptime(date_string[-17:-4], "%Y%m%d-%H%M") for date_string in raster_paths]
timestamps = [int(time.timestamp()) for time in times]

In [5]:
# occurrence des changements

raster_arrays = []
for path in raster_paths:
    with rasterio.open(path) as src:
        raster_arrays.append(src.read(1))

# Initialize counters for changes from 1 to 0 and 0 to 1
changes_1_to_0 = np.zeros_like(raster_arrays[0])
changes_0_to_1 = np.zeros_like(raster_arrays[0])

# Compare corresponding pixels across the arrays to identify changes
for i in range(len(raster_arrays) - 1):
    changes_1_to_0 += np.logical_and(raster_arrays[i] == 1, raster_arrays[i + 1] == 0)
    changes_0_to_1 += np.logical_and(raster_arrays[i] == 0, raster_arrays[i + 1] == 1)

In [6]:
#create 4 rasters

first_sun = np.full((height, width), 0.)  # Initialize with infinity
first_shadow = np.full((height, width), 0.)  # Initialize with infinity
second_sun = np.full((height, width), 0.)
second_shadow = np.full((height, width), 0.)
# previous_mask = np.full((height, width), 1.) # Initialize to dark

# Iterate through the input rasters
for path,timestamp in zip(raster_paths,timestamps):
    with rasterio.open(path) as src:
        data = src.read(1)  # Read the raster data
        mask_first_sun = (first_sun == 0.) & (data == 0.)  # Identify pixels changing from 1 to 0
        mask_first_shadow = (first_shadow == 0.) & (first_sun != 0.) & (data == 1.)  # Identify pixels changing from 0 to 1
        mask_second_sun = (second_sun == 0.) & (first_shadow != 0.) & (data == 0.)  # Identify pixels changing from 0 to 1
        mask_second_shadow = (second_shadow == 0.) & (second_sun != 0.) & (data == 1.)  # Identify pixels changing from 0 to 1
        
        
        first_sun[mask_first_sun] = timestamp # Update time for pixels changing from 1 to 0
        first_shadow[mask_first_shadow] = timestamp # Update time for pixels changing from 0 to 1
        second_sun[mask_second_sun] = timestamp # Update time for pixels changing from 1 to 0
        second_shadow[mask_second_shadow] = timestamp # Update time for pixels changing from 0 to 1
        

In [8]:
mask = changes_0_to_1 + changes_1_to_0 > 4

In [8]:
mask.sum() / mask.size *100

1.3514

In [9]:
# set pixels with too much changes to NaN
first_sun[mask] = -1
first_shadow[mask] = -1
second_sun[mask] = -1
second_shadow[mask] = -1

In [10]:
# stack rasters for poligonization
stacked_rasters = np.stack([first_sun, first_shadow, second_sun, second_shadow], axis=2)

coded_raster, dictionnary = coded_raster(stacked_rasters)

In [29]:
# save raster
profile['dtype'] = 'int32'
with rasterio.open('coded_raster.tif', 'w', **profile) as dst:
    dst.write(coded_raster, 1)

In [69]:
profile['dtype'] = 'float64'
with rasterio.open('first_sun_timestamp.tif', 'w', **profile) as dst:
    dst.write(first_sun, 1)
with rasterio.open('first_shadow_timestamp.tif', 'w', **profile) as dst:
    dst.write(first_shadow, 1)
with rasterio.open('second_sun_timestamp.tif', 'w', **profile) as dst:
    dst.write(second_sun, 1)
with rasterio.open('second_shadow_timestamp.tif', 'w', **profile) as dst:
    dst.write(second_shadow, 1)

In [2]:
# Read coded geoms
chunks = gpd.read_file("coded_geoms.gpkg")

In [4]:
import subprocess

t1 = time.time()
command = 'ogr2ogr output_dissolved.gpkg coded_geoms.gpkg -dialect sqlite -sql "SELECT ST_Union(geom), code FROM coded_geoms GROUP BY code" -f "GPKG"'
subprocess.run(command, shell=True)
t2 = time.time()
print(t2-t1)

Warning 1: A geometry of type POLYGON is inserted into layer SELECT of geometry type MULTIPOLYGON, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.


317.83913397789


In [3]:
# dissolve geometries
t1 = time.time()
chunks.dissolve('code').to_file('coded_geoms_dissolved.gpkg')
t2 = time.time()
print(t2-t1)

499.4431722164154


In [44]:
import geopandas as gpd
from concurrent.futures import ProcessPoolExecutor

# Specify the file path
file_path = "coded_geoms.gpkg"

# Define the number of processes to use
num_processes = 4  # Adjust as needed based on your available resources

def read_geopackage_chunk(chunk):
    return gpd.read_file(chunk)

# Read the GeoPackage file in chunks
chunks = gpd.read_file(file_path, chunksize=1000)  # Adjust the chunksize as needed

# Use multiprocessing to parallelize the read operation
with ProcessPoolExecutor(max_workers=32) as executor:
    # Submit read operations for each chunk
    futures = [executor.submit(read_geopackage_chunk, chunk) for chunk in chunks]

    # Wait for all tasks to complete
    gdfs = [future.result() for future in futures]

# Concatenate the GeoDataFrames obtained from different chunks
result_gdf = gpd.concat(gdfs, ignore_index=True)

# Now 'result_gdf' contains the concatenated GeoDataFrame

DriverError: code: No such file or directory

# passage au format vecteur 

In [120]:
import geopandas as gpd
#poligonize the raster with float values

#change the shadow_to_sun_time column
gdf = gpd.read_file('start_sun_timestamp.gpkg')

gdf['time'] = gdf['time'].mask(gdf['time'] < 0, np.nan)

gdf['time'] = gdf['time'].apply(lambda x: datetime.fromtimestamp(x).replace(second=0).strftime('%Y-%m-%d %H:%M:%S') if not np.isnan(x) else "")

gdf.dissolve('time').to_file('start_sun_timestamp_dissolved.gpkg')

In [121]:
import geopandas as gpd

gdf = gpd.read_file('end_sun_timestamp.gpkg')

gdf['time'] = gdf['time'].mask(gdf['time'] < 0, np.nan)

gdf['time'] = gdf['time'].apply(lambda x: datetime.fromtimestamp(x).replace(second=0).strftime('%Y-%m-%d %H:%M:%S') if not np.isnan(x) else "")

gdf.dissolve('time').to_file('end_sun_timestamp_dissolved.gpkg')

# Intersection des deux rasters

In [122]:
intersection = gpd.overlay(gpd.read_file('start_sun_timestamp_dissolved.gpkg'), gpd.read_file('end_sun_timestamp_dissolved.gpkg'), how='intersection')

intersection.to_file('intersection_start_end_sun.gpkg')

/usr/local/lib/python3.8/dist-packages/geopandas/geodataframe.py:1803: FutureWarning: `unary_union` returned None due to all-None GeoSeries. In future, `unary_union` will return 'GEOMETRYCOLLECTION EMPTY' instead.
  merged_geom = block.unary_union
/tmp/slurm-3838576/ipykernel_1651519/3484396975.py:1: UserWarning: `keep_geom_type=True` in overlay resulted in 1334486 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  intersection = gpd.overlay(gpd.read_file('start_sun_timestamp_dissolved.gpkg'), gpd.read_file('end_sun_timestamp_dissolved.gpkg'), how='intersection')


In [36]:
intersection = gpd.read_file('intersection_start_end_sun.gpkg')

In [123]:
intersection['time_1'] = intersection['time_1'].apply(lambda x: '2024-05-31 23:59:59' if x == '1970-01-01 00:00:00' else x)
intersection['time_2'] = intersection['time_2'].apply(lambda x: '2024-05-31 23:59:59' if x == '1970-01-01 00:00:00' else x)

In [125]:
intersection.drop(0).to_file('intersection_start_end_sun_rectified.gpkg')

# GIF animation

In [131]:
from PIL import Image
import glob
# List of image file names
image_files = sorted(glob.glob('carte_ensoleillement*.png'))[2:-1]
print(len(image_files))
# Open each image and append to a list
images = []
for filename in image_files:
    images.append(Image.open(filename))

# Save the images as an animated GIF
images[0].save('animated.gif', save_all=True, append_images=images[1:], duration=1000, loop=20)

22


# filter small polygons

In [6]:
# simple filter
threshold = 2
geom = intersection.iloc[13].geometry
gpd.GeoDataFrame(geometry=[MultiPolygon([polygon for polygon in geom.geoms if polygon.area > threshold])]).to_file('multipoly_example.gpkg')


In [17]:
# convex hull before filter
threshold = 2
geom = intersection.iloc[13].geometry
gpd.GeoDataFrame(geometry=[MultiPolygon([polygon.convex_hull for polygon in geom.geoms if polygon.area > threshold])]).to_file('multipoly_example_convex_hull.gpkg')

In [24]:
# smooth before filter
threshold = 2
geom = intersection.iloc[13].geometry
gpd.GeoDataFrame(geometry=[MultiPolygon([polygon.simplify(tolerance=0.3) for polygon in geom.geoms if polygon.area > threshold])]).to_file('multipoly_example_smoothen.gpkg')

# Combinaison des deux rasters

In [35]:
rasters_stacked = np.dstack((start_sun, end_sun))

In [52]:
np.unique(np.reshape(rasters_stacked, (-1, rasters_stacked.shape[2])), axis=0)

364118

In [55]:
keys = np.unique([rasters_stacked[i][i] for i in range(rasters_stacked.shape[0])], axis=0)

In [65]:
len(keys[~np.isnan(keys).any(axis=1)])

238

# Test de la technique quadruplet

In [33]:
import numpy as np

# Initialize four random arrays of size 10x10
array1 = np.random.randint(0, 3, size=(10,10))
array2 = np.random.randint(0, 3, size=(10,10))
array3 = np.random.randint(0, 3, size=(10,10))
array4 = np.random.randint(0, 3, size=(10,10))

# Stack the arrays along a new axis (axis=2 in this case)
stacked_array = np.stack([array1, array2, array3, array4], axis=2)

# Display the individual arrays and the stacked array
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nArray 3:\n", array3)
print("\nArray 4:\n", array4)

print("\nStacked Array:\n", stacked_array[0,0,:])

Array 1:
 [[2 0 1 2 1 2 2 2 2 2]
 [1 2 2 1 0 1 2 2 1 0]
 [2 2 2 1 0 0 1 2 0 0]
 [1 1 1 1 0 0 1 1 1 2]
 [2 1 0 1 0 0 2 0 0 0]
 [2 0 1 2 2 1 1 0 1 0]
 [1 0 2 2 1 0 0 1 0 2]
 [1 1 0 2 2 1 2 0 0 2]
 [2 0 1 1 2 1 2 2 0 0]
 [0 0 2 0 1 0 1 0 2 2]]

Array 2:
 [[1 2 1 0 2 0 1 2 0 0]
 [0 0 1 2 1 2 0 0 0 1]
 [0 2 2 2 2 0 1 2 2 1]
 [2 0 1 2 2 0 1 2 2 1]
 [0 0 1 1 2 0 0 1 0 1]
 [1 1 1 0 2 0 1 2 0 2]
 [2 0 0 1 2 2 2 2 2 1]
 [2 2 0 1 0 0 2 1 2 2]
 [1 1 1 2 0 1 0 2 0 0]
 [1 1 2 2 0 2 0 1 1 0]]

Array 3:
 [[2 1 1 1 1 2 2 0 2 0]
 [0 1 0 0 2 0 1 1 0 0]
 [1 1 2 2 2 1 2 1 1 0]
 [2 2 0 0 2 2 0 2 0 2]
 [0 1 0 0 0 1 0 0 0 2]
 [0 0 1 1 2 1 0 2 1 2]
 [2 2 1 2 1 1 2 2 1 0]
 [1 0 2 1 2 0 2 2 2 2]
 [2 1 1 0 0 1 2 0 1 2]
 [1 0 1 2 1 2 1 1 0 0]]

Array 4:
 [[1 0 0 0 0 2 0 1 1 2]
 [0 1 1 2 2 0 0 2 2 1]
 [2 1 0 0 2 0 0 2 0 2]
 [0 1 2 0 0 1 0 1 1 2]
 [2 2 1 0 1 1 1 0 0 0]
 [1 0 2 1 1 1 2 0 1 1]
 [2 2 2 0 1 2 0 0 1 1]
 [2 1 2 2 1 0 1 2 0 0]
 [1 0 1 0 0 0 1 0 2 1]
 [1 1 2 1 2 1 2 1 0 1]]

Stacked Array:
 [2 1 2 1]


In [53]:
def coded_raster(stacked_array):
    # reshape array
    data_2d = stacked_array.reshape(-1, 4)

    # get quadruples
    unique_quadruplets, _ = np.unique(data_2d, axis=0, return_inverse=True)
    
    # create dict
    quadruplet_dict = {tuple(q): i + 1 for i, q in enumerate(unique_quadruplets)}
    
    # create coded raster
    new_array = np.array([[quadruplet_dict[tuple(stacked_array[i, j, :])] for j in range(stacked_array.shape[1])] for i in range(stacked_array.shape[0])])

    return new_array, quadruplet_dict

# Improving dissolve

In [123]:
chunks = gpd.read_file("coded_geoms.gpkg", chunksize=10)


KeyboardInterrupt



In [124]:
dissolved = gpd.read_file("coded_geoms_dissolved.gpkg")

In [129]:
import multiprocessing 
import dask.dataframe as dd


multiprocessing.cpu_count()

128

In [160]:
chunk = dissolved

In [137]:
dictionnary = {v: k for k, v in dictionnary.items()}


In [161]:
# Fonction pour récupérer le quadruplé à partir du dictionnaire
def get_quadruplet(code):
    return pd.Series(dictionnary.get(code, [None, None, None, None]), index=['first_sun_appearance', 'first_shadow_appearance', 'second_sun_appearance', 'second_shadow_appearance'])

# Appliquer la fonction à la colonne 'code'
chunk[['first_sun_appearance', 'first_shadow_appearance', 'second_sun_appearance', 'second_shadow_appearance']] = chunk['code'].apply(get_quadruplet)

chunk = chunk.drop(columns='code')

In [48]:
times

[datetime.datetime(2024, 5, 31, 8, 0),
 datetime.datetime(2024, 5, 31, 8, 30),
 datetime.datetime(2024, 5, 31, 9, 0),
 datetime.datetime(2024, 5, 31, 9, 30),
 datetime.datetime(2024, 5, 31, 10, 0),
 datetime.datetime(2024, 5, 31, 10, 30),
 datetime.datetime(2024, 5, 31, 11, 0),
 datetime.datetime(2024, 5, 31, 11, 30),
 datetime.datetime(2024, 5, 31, 12, 0),
 datetime.datetime(2024, 5, 31, 12, 30),
 datetime.datetime(2024, 5, 31, 13, 0),
 datetime.datetime(2024, 5, 31, 13, 30),
 datetime.datetime(2024, 5, 31, 14, 0),
 datetime.datetime(2024, 5, 31, 14, 30),
 datetime.datetime(2024, 5, 31, 15, 0),
 datetime.datetime(2024, 5, 31, 15, 30),
 datetime.datetime(2024, 5, 31, 16, 0),
 datetime.datetime(2024, 5, 31, 16, 30),
 datetime.datetime(2024, 5, 31, 17, 0),
 datetime.datetime(2024, 5, 31, 17, 30),
 datetime.datetime(2024, 5, 31, 18, 0),
 datetime.datetime(2024, 5, 31, 18, 30),
 datetime.datetime(2024, 5, 31, 19, 0),
 datetime.datetime(2024, 5, 31, 19, 30),
 datetime.datetime(2024, 5, 31, 

In [ ]:
sun_times = gpd.read_file('../outputs/JO/sun_times.gpkg')

In [ ]:
sun_times

In [51]:
cols = ['first_sun_appearance', 'first_shadow_appearance', 'second_sun_appearance', 'second_shadow_appearance']
sun_times[cols] = sun_times[cols].applymap(lambda x: pd.to_datetime(x, unit='s') if x > 0 else np.nan if x == -1 else times[0].replace(hour=23, minute=59, second=59))

In [1]:
def sec_to_hms(t):
    h = int(t // 3600)
    m = int((t - h * 3600) // 60)
    s = t - h * 3600 - m * 60

    h = "0" + str(h) if h < 10 else h
    m = "0" + str(m) if m < 10 else m
    s = "0" + str(s) if s < 10 else s

    return "{}:{}:{:.3}".format(h, m, s)

In [8]:
def seconds_to_hhmmss(seconds):
    hours = seconds // 3600
    seconds %= 3600
    minutes = seconds // 60
    seconds %= 60
    return '{:02d}:{:02d}:{:02d}.{:02d}'.format(int(hours), int(minutes), int(seconds), int((seconds - int(seconds)) * 100))


total_seconds = 3665.7894494  # Replace with the actual duration in seconds
formatted_time = seconds_to_hhmmss(total_seconds)
print(formatted_time)

01:01:05.78


In [2]:
# Assuming your original 3D list is called original_list
original_list = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
]

# Inverting dimensions 1 and 2
inverted_list = [[[original_list[i][j][k] for j in range(len(original_list[i]))] for i in range(len(original_list))] for k in range(len(original_list[0][0]))]

# Print the inverted list
print(inverted_list)

[[[1, 4], [7, 10], [13, 16]], [[2, 5], [8, 11], [14, 17]], [[3, 6], [9, 12], [15, 18]]]


In [ ]:
# Assuming your list is called nested_list
import itertools
# Flatten the first dimension
flattened_list = list(itertools.chain.from_iterable(original_list))

# Print the flattened list
print(flattened_list)

# reduce mask storage

In [44]:
from osgeo import gdal
import rasterio
# Assuming 'mask_data' is your binary mask raster with values 0 and 1

with rasterio.open('../../outputs/JO/test_bytes/75-2021-0653-6866-LA93-0M50-hillshade-20240726-1100.tif') as src:
        # Read the image data
        mask_data = src.read(1)
        profile = src.profile
        
# # Define the raster dimensions
# width = mask_data.shape[1]
# height = mask_data.shape[0]

# # Create a new GeoTIFF file
# driver = gdal.GetDriverByName('GTiff')
# bitmask_ds = driver.Create('../../outputs/JO/test_bytes/mask.tif', width, height, 1, gdal.GDT_Byte)

# # Set the GeoTransform (optional)
# # bitmask_ds.SetGeoTransform(...)

# # Write the data to the band
# bitmask_band = bitmask_ds.GetRasterBand(1)
# bitmask_band.WriteArray(mask_data)

# # Close the dataset
bitmask_ds = None


In [38]:
profile

{'driver': 'GTiff', 'dtype': 'float32', 'nodata': -99999.0, 'width': 2000, 'height': 2000, 'count': 1, 'crs': CRS.from_epsg(2154), 'transform': Affine(0.5, 0.0, 653000.0,
       0.0, -0.5, 6866000.0), 'blockxsize': 1024, 'blockysize': 1024, 'tiled': True, 'compress': 'lzw', 'interleave': 'band'}

In [39]:
mask_data = mask_data.astype(np.uint8)

In [40]:
profile['dtype']= 'uint8'
profile['nodata'] = 2

In [43]:
with rasterio.open('../../outputs/JO/test_bytes/mask3.tif', 'w', **profile) as dst:
    dst.write(mask_data, 1)

In [55]:
np.round(mask_data*32.4).astype(np.uint8)

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0, 32, 32, ..., 32,  0,  0],
       [32, 32, 32, ..., 32,  0,  0],
       [32, 32, 32, ..., 32,  0,  0]], dtype=uint8)

In [13]:
from PIL import Image, ImageDraw, ImageFont
import os
import glob

# List of TIF files
tif_files = sorted(glob.glob("/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-*.tif"))
print(tif_files)

# Labels for each image
labels = ["Label 1", "Label 2", "Label 3", "Label 4", "Label 5", "Label 6", "Label 7", "Label 8", "Label 9", "Label 10", "Label 11", "Label 12", "Label 13", "Label 14"]

# Open each TIF file, add label, and save as GIF
frames = []
for tif_file, label in zip(tif_files, labels):
    image = Image.open(tif_file).convert('RGB')
    frames.append(image)

# Save GIF
gif_path = "output.gif"
frames[0].save(gif_path, append_images=frames[1:], save_all=True, duration=1000, loop=0)  # Duration in milliseconds, loop=0 for infinite loop

print("GIF created:", gif_path)


['/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-0700.tif', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-0800.tif', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-0900.tif', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-1000.tif', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-1100.tif', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-1200.tif', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hillshade-20240803-1300.tif', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/JO/test_sunmap3/75-2021-0645-6860-LA93-0M50-hills

In [12]:
from PIL import Image
import glob
# List of image file names
image_files = sorted(glob.glob('carte_ensoleillement*.png'))[2:-1]
print(len(image_files))
# Open each image and append to a list
images = []
for filename in image_files:
    images.append(Image.open(filename).convert('RGB'))

# Save the images as an animated GIF
images[0].save('animated.gif', save_all=True, append_images=images[1:], duration=1000, loop=20)

0


IndexError: list index out of range

In [4]:
from PIL import Image
import glob
# List of image file names
image_files = sorted(glob.glob('../imgs/carte_ensoleillement*.png'))
print(len(image_files))
# Open each image and append to a list
images = []
for filename in image_files:
    images.append(Image.open(filename))

# Save the images as an animated GIF
images[0].save('animated.gif', save_all=True, append_images=images[1:], duration=1000, loop=20)

14


In [2]:
image_files

['../imgs/carte_ensoleillement0000.png',
 '../imgs/carte_ensoleillement0001.png',
 '../imgs/carte_ensoleillement0002.png',
 '../imgs/carte_ensoleillement0003.png',
 '../imgs/carte_ensoleillement0004.png',
 '../imgs/carte_ensoleillement0005.png',
 '../imgs/carte_ensoleillement0006.png',
 '../imgs/carte_ensoleillement0007.png',
 '../imgs/carte_ensoleillement0008.png',
 '../imgs/carte_ensoleillement0009.png',
 '../imgs/carte_ensoleillement0010.png',
 '../imgs/carte_ensoleillement0011.png',
 '../imgs/carte_ensoleillement0012.png',
 '../imgs/carte_ensoleillement0013.png']

In [8]:
import geopandas as gpd
import os
import shutil

img = gpd.read_file('/work/EOLAB/DATA/MNS/Montpellier/dalles.shp')['NOM_DALLE']
for f in img:
    shutil.move('/work/EOLAB/DATA/MNS/Herault/' + f, '/work/EOLAB/DATA/MNS/Montpellier')

In [12]:
def save_list_to_file(file_list, file_path):
    with open(file_path, 'w') as f:
        for item in file_list:
            f.write("/work/EOLAB/DATA/MNS/Montpellier/%s\n" % item)

# Example usage:
file_list = list(gpd.read_file('../../Montpellier/dalles_centre_ville.shp')['NOM_DALLE'])
file_path = "../../sun_map_generation/listings/listing_montpellier.lst"  # Path to save the list file

save_list_to_file(file_list, file_path)


In [1]:
import glob 
# import geopandas as gpd
import subprocess


# vectors = gpd.read_file('/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-0645-6861-LA93-0M50-sun_times-20240721.gpkg')

In [22]:
files

['/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-0643-6864-LA93-0M50-sun_times-20240721.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-0654-6867-LA93-0M50-sun_times-20240721.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-0655-6868-LA93-0M50-sun_times-20240721.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-0646-6863-LA93-0M50-sun_times-20240721.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-0661-6860-LA93-0M50-sun_times-20240721.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-0657-6861-LA93-0M50-sun_times-20240721.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique/21072024/0820/75-2021-066

In [27]:
files = glob.glob("/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique_v2/21062024/0820/75*.gpkg")

In [28]:
len(files)

138

In [14]:
(cast("first_sun_appearance" as character) < '2024-08-
03T12:00:00' AND cast("first_shadow_appearance" as 
character) > '2024-08-03T16:00:00') or 
(cast("second_sun_appearance" as character) < '2024-08-
03T12:00:00' AND cast("second_shadow_appearance" as 
character) > '2024-08-03T16:00:00')

['/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/vegetalisation_v2/01072024/75-2021-0646-6864-LA93-0M50-sun_times-20240701.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/vegetalisation_v2/01072024/75-2021-0647-6860-LA93-0M50-sun_times-20240701.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/vegetalisation_v2/01072024/75-2021-0654-6867-LA93-0M50-sun_times-20240701.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/vegetalisation_v2/01072024/75-2021-0647-6863-LA93-0M50-sun_times-20240701.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/vegetalisation_v2/01072024/75-2021-0652-6859-LA93-0M50-sun_times-20240701.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/vegetalisation_v2/01072024/75-2021-0657-6864-LA93-0M50-sun_times-20240701.gpkg',
 '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/vegetalisation_v2/01072024/75-2021-0652-6864-LA93-0M

In [29]:
for file in files:
    layer = file.split('/')[-1][:-5]
    print(layer)
    command = [
        'ogr2ogr',
        '-f', 'GPKG',
        '-dialect', 'SQLite',
        '-sql', f'SELECT * FROM "{layer}" WHERE (CAST("first_sun_appearance" AS TEXT) < \'2024-06-21T12:00:00\' AND CAST("first_shadow_appearance" AS TEXT) > \'2024-06-21T16:00:00\') OR (CAST("second_sun_appearance" AS TEXT) < \'2024-06-21T12:00:00\' AND CAST("second_shadow_appearance" AS TEXT) > \'2024-06-21T16:00:00\')',
        f'/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique_v2/21062024/0820/{layer}_sans_ombres_12h_16h.gpkg',
        file
    ]
    print(command)
    subprocess.run(command, capture_output=True, text=True, check=True)

75-2021-0656-6863-LA93-0M50-sun_times-20240621
['ogr2ogr', '-f', 'GPKG', '-dialect', 'SQLite', '-sql', 'SELECT * FROM "75-2021-0656-6863-LA93-0M50-sun_times-20240621" WHERE (CAST("first_sun_appearance" AS TEXT) < \'2024-06-21T12:00:00\' AND CAST("first_shadow_appearance" AS TEXT) > \'2024-06-21T16:00:00\') OR (CAST("second_sun_appearance" AS TEXT) < \'2024-06-21T12:00:00\' AND CAST("second_shadow_appearance" AS TEXT) > \'2024-06-21T16:00:00\')', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique_v2/21062024/0820/75-2021-0656-6863-LA93-0M50-sun_times-20240621_sans_ombres_12h_16h.gpkg', '/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/VilleParis/chgtclimatique_v2/21062024/0820/75-2021-0656-6863-LA93-0M50-sun_times-20240621.gpkg']
75-2021-0652-6864-LA93-0M50-sun_times-20240621
['ogr2ogr', '-f', 'GPKG', '-dialect', 'SQLite', '-sql', 'SELECT * FROM "75-2021-0652-6864-LA93-0M50-sun_times-20240621" WHERE (CAST("first_sun_appearance" AS TEXT) < \'2024-06-21T12

In [2]:
import geopandas as gpd
from shapely.geometry import Polygon

def get_neighbors(gdf, tile_name):
    # Trouver la dalle cible
    target_tile = gdf[gdf['NOM_DALLE'] == tile_name]
    
    if target_tile.empty:
        raise ValueError(f"No tile found with name {tile_name}")
    
    # Calculer le bounding box de la dalle cible
    target_bounds = target_tile.geometry.bounds.values[0]

    # Filtrer les dalles dans le bounding box étendu
    minx, miny, maxx, maxy = target_bounds
    buffered_bounds = gdf.cx[minx-1:maxx+1, miny-1:maxy+1]

    # Filtrer les dalles adjacentes
    neighbors = buffered_bounds[buffered_bounds.touches(target_tile.geometry.squeeze())]

    return neighbors['NOM_DALLE'].tolist()

# Charger le fichier de dalles
tiles_file = "/work/EOLAB/DATA/MNS/Paris/dalles.shp"
gdf = gpd.read_file(tiles_file)

# Nom de la dalle cible
tile_name = "75-2021-0649-6862-LA93-0M50.tif"

# Récupérer les voisins
neighbors = get_neighbors(gdf, tile_name)
print(f"Neighbors of {tile_name}: {neighbors}")


Neighbors of 75-2021-0649-6862-LA93-0M50.tif: ['75-2021-0648-6861-LA93-0M50.tif', '75-2021-0648-6862-LA93-0M50.tif', '75-2021-0648-6863-LA93-0M50.tif', '75-2021-0649-6861-LA93-0M50.tif', '75-2021-0649-6863-LA93-0M50.tif', '75-2021-0650-6861-LA93-0M50.tif', '75-2021-0650-6862-LA93-0M50.tif', '75-2021-0650-6863-LA93-0M50.tif']


In [ ]:
merge_command = ['gdal_merge', '-o', 

In [ ]:
subprocess.run(merge_command,shell=True)

In [6]:
import rasterio
import rasterio.mask
dalles = gpd.read_file("/work/EOLAB/DATA/MNS/Paris/dalles.shp")
target_tile = gdf[gdf['NOM_DALLE'] == "75-2021-0649-6862-LA93-0M50.tif"]
# shapes = [feature["geometry"] for feature in shapefile]

with rasterio.open("/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/outputs/test/75-2021-0649-6862-LA93-0M50-hillshade-20240831-0800.tif") as src:
    out_image, out_transform = rasterio.mask.mask(src, target_tile['geometry'], crop=True)
    mask_data = out_image[0,:,:]
    out_meta = src.meta

ValueError: Input shapes do not overlap raster.

In [8]:
!pip install geopandas

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip


In [4]:
import geopandas as gpd

gpd.read_file("/work/EOLAB/USERS/duthoit/CARTE_ENSOILLEMENT/livraison/vegetalisation/dissolved.gpkg")

DriverError: database is locked